#!/bin/sh
# Copy launch-video media from the world templates into public/ (gitignored).
# Run from video/remotion:  npm run sync
set -u
R=../..
T=$R/templates
P=public
mkdir -p $P/cast $P/bg $P/scenes $P/portraits $P/sfx $P/music $P/footage

C=motion/seedance/characters
cp $T/wuwu/assets/$C/viola-transparent.webm              $P/cast/vera.webm
cp $T/first-snow/assets/$C/sumi-transparent.webm         $P/cast/sumi.webm
cp $T/first-snow/assets/$C/nanami-transparent.webm       $P/cast/nanami.webm
cp $T/whitechapel/assets/$C/watson-transparent.webm      $P/cast/watson.webm
cp $T/magic-academy/assets/$C/seraphina-transparent.webm $P/cast/seraphina.webm
cp $T/divergence/assets/$C/ryo-transparent.webm          $P/cast/ryo.webm

for w in wuwu whitechapel first-snow divergence; do
  mkdir -p $P/bg/$w
  cp $T/$w/assets/motion/seedance/backgrounds/*.webm $P/bg/$w/
  cp $T/$w/assets/characters/*.webp $P/portraits/
done
cp $T/magic-academy/assets/$C/seraphina-transparent.webp $P/portraits/seraphina.webp

for w in wuwu whitechapel first-snow divergence magic-academy; do
  for d in scenes backgrounds; do
    [ -d $T/$w/assets/$d ] || continue
    for f in $T/$w/assets/$d/*; do
      [ -f "$f" ] && cp "$f" "$P/scenes/$w-$(basename "$f")"
    done
  done
done

cp $R/assets/audio/foley/*.mp3 $R/assets/audio/foley/canvas/*.mp3 $P/sfx/

# Footage captured into video/footage/claude/ is mirrored here too.
[ -d $R/video/footage/claude ] && cp -R $R/video/footage/claude/. $P/footage/

# ── Launcher covers (scenes/parts/Launcher.tsx) — each template's launcher cover: world.json `cover`,
#    else the intro / first image in assets/scenes or assets/backgrounds (apps/server/src/world-shelf.ts).
mkdir -p $P/covers
cp $T/wuwu/assets/scenes/intro.webp                 $P/covers/wuwu.webp
cp $T/whitechapel/assets/scenes/intro.webp          $P/covers/whitechapel.webp
cp $T/first-snow/assets/scenes/intro.webp           $P/covers/first-snow.webp
cp $T/divergence/assets/scenes/intro.webp           $P/covers/divergence.webp
cp $T/magic-academy/assets/scenes/academy-library.webp $P/covers/magic-academy.webp
cp $T/unwritten-door/assets/backgrounds/intro.png   $P/covers/unwritten-door.png
cp $T/moonlit-contract/assets/backgrounds/opening.png $P/covers/moonlit-contract.png

# Unwritten Door: the realistic door for the gate effect (S6 Round 4).
mkdir -p $P/bg/unwritten-door && cp $T/unwritten-door/assets/motion/seedance/backgrounds/intro.webm $P/bg/unwritten-door/
cp $T/unwritten-door/assets/tokens/door.png $P/scenes/unwritten-door.png
# AI ROLEPLAY icon: Nanami as a black-and-white manga cut-out (A7 formula).
mkdir -p $P/icons && ffmpeg -loglevel error -y -i $T/first-snow/assets/motion/seedance/characters/nanami-transparent.webp -filter_complex "crop=330:330:135:40,split[a][b];[a]alphaextract[m];[b]format=gray,eq=contrast=2.2:brightness=0.08,lutyuv=y='if(gt(val,120),255,0)'[g];[g][m]alphamerge,format=rgba,scale=256:256" $P/icons/roleplay-nanami.png
# Wataru (otome love interest, voice demo): a scene loop supplied by the user, kept in video/assets.
cp $R/video/assets/wataru-loop.scene.mp4 $P/cast/wataru.mp4
# 3D dice model (parts/Dice3D.tsx).
mkdir -p $P/models && cp $R/assets/models/arcane-d10/noctiluca-d10.glb $P/models/
# Voice lines (public/voice) are generated by: node ../music/make-voices.mjs

echo "synced into $P"
