import { author } from './common.mjs';
const p = author('unwritten-door', 'The Unwritten Door · Playtest', 'An unopened letter and a phone shape the place that waits outside. One door, one living new scene.', 'en');
p.scene('world', 'The Cabin', 'You wake at a wooden table. Rain touches the roof. A sealed envelope, a dark phone, one unlocked door. Your head aches; how you arrived is not yet a fact.\n\nYou can learn something before leaving—or turn the handle without knowing.', [], { bg: 'assets/backgrounds/intro.png', intent: 'The letter and phone are the only investigative props. Furniture is atmosphere, not extra puzzles. Do not decide the player identity or supernatural explanation in advance.', appearance: { font: 'hand', surface: 'none', accent: 'ink', ornament: 'underline', motion: 'still' } });
p.put('world/letter.md', { type: 'letter', title: 'The sealed envelope', visual: 'envelope', portable: true, choice: ['Open the envelope', 'Examine the outside'], status: { data: { opened: false } }, intent: 'Only opening reveals a short concrete message. Persist the full message, public Context and opened=true. Looking outside is not opening. On revisit keep the same text.', appearance: { preset: 'parchment-letter', motion: 'calm' } }, 'An envelope addressed in unfamiliar handwriting.\n\n## Context\nThe letter has not been opened.');
p.put('world/phone.md', { type: 'note', title: 'The phone', visual: 'phone', portable: true, choice: ['Wake the screen', 'Call the last number'], status: { data: { contacted: false } }, intent: 'Screen inspection reveals limited information. A fictional call records actual words, one concrete audible detail, public Context and contacted=true. It is not a real telephone call.' }, 'A black phone lies face down.\n\n## Context\nNo information has been discovered.');
p.put('world/door.md', { type: 'gate', title: 'The door', target: 'world/outside', visual: 'door', portable: false, intent: 'Read discovered letter and phone Context. Enter the existing outside stub, generating only its first place. If partially generated, repair missing files instead of changing the place.' }, 'The handle turns. The door is not locked. The world outside has not been described yet.');
p.files['world/outside/.gitkeep'] = '';
p.rules(`## Envelope and phone
Read their current locations even if moved to player/. Opening the envelope creates one short contemporary message containing a place or person and a personal stake. Update the actual item with the message and public Context. Merely examining its outside does not reveal the message. A phone call is fictional roleplay; persist the actual exchange and one concrete sound or spoken landmark. Neither object secretly contributes facts before discovery.

## Opening the door
The only initial expansion is world/outside. Read both actual items and their public Context again. If unused, contribute no hidden facts. If a letter was opened, respect its place or person. If a call happened, reflect its audible detail or landmark. If both happened, honour both. If neither happened, create a plausible contemporary place with one small opportunity; do not punish curiosity or invent a cult by default.

Write world/outside/README.md, resident.md, found-object.md, 01-arrival.md and return.md. The return gate targets map. The resident is a nonportable note: name, present activity, one line they can say and what they do not know. The found object should connect to a revealed detail without revealing the entire mystery. The arrival Chalk offers talk, inspect and return; its intent allows only one explicitly motivated further discovery, not an infinite tree. Add one concrete line to the parent door explaining what is now beyond it.

Verify all five files, even when README already exists. Repair a partial scene without inventing a different resident or geography. Text completion precedes one generate_image call: restrained cinematic contemporary atmosphere, the actual weather and objects, no UI or lettering. Do not make the phone or letter a giant background prop. Store the returned asset in README bg. Missing image is a visible pending illustration, not a fabricated success.

## First-minute reward
When the player talks to the resident, quote a detail the player really supplied or noticed, then update resident.md with what they learned. Inspecting the found object yields one usable fact or small item, not a solved conspiracy. The punch line is recognising something from inside in a newly materialised outside. Returning uses map and preserves the outside. No campaign ending is required.`);
p.checks.push({ kind: 'stub', path: 'world/outside' });
export default p;
