export type Locale = 'en' | 'ja';

export const UI_COPY = {
  en: {
    sceneChalk: 'Scene Chalk',
    collapseScene: 'Fold scene introduction',
    expandScene: 'Read scene introduction',
    world: 'World',
    back: 'Back one scene',
    writerPlaceholder: 'Tell the writer what you do…',
    writerWriting: 'The writer is writing…',
    ghostReused: 'Already had this image',
    ghostFailed: 'The picture could not be drawn.',
    ghostUnreachable: 'The picture could not be shown.',
    sentToWriter: 'Sent to the writer',
    take: 'Take',
    taken: 'Added to backpack',
    backpack: 'Backpack',
    characters: 'Characters',
    backpackHint: 'Drag an item onto a card or character. Drop it on the canvas to put it back.',
    backpackEmpty: 'Your backpack is empty. Take an object from the scene first.',
    controls: 'Drag to pan · Scroll to zoom · Click a door to enter · Alt+← / Esc to return · Type below to act',
    language: '日本語',
    mute: 'Mute sound',
    unmute: 'Unmute sound',
    godHand: 'God Hand',
    worldFrozen: 'World Frozen',
    pauseWorld: 'Pause world agents',
    thawWorld: 'World is paused. Click to thaw',
    showControls: 'Show controls help',
    hideControls: 'Hide controls help',
    timestamp: 'Day 1 · Rain Subsides 17:40',
    material: 'material',
    minimap: 'MINIMAP',

    nook: 'Nook',
    nookBack: 'Leave the nook',
    nookEmptyTitle: 'Nothing here yet',
    nookEmptyBody: 'Traces of moving in, and nothing else.',
    nookEmptyPrompt: 'What should there be, here?',
    nookEmptyHint: 'Leave it blank — what fits their history will appear.',
    nookInitSkip: 'Skip',
    nookGenerating: 'Taking shape…',
    nookInitFailed: 'It never quite took shape here.',
    nookError: 'Could not open this nook',
    nookRetry: 'Try again',
    nookCoreStatus: 'Currently here',

    liveCallStart: 'Speak aloud',
    liveCallStop: 'Hang up',
    liveCallConnecting: 'Connecting…',
    liveCallLive: 'On a call',
    liveCallYou: 'You',
    liveCallThem: 'They say',
    liveCallModalBlocked: 'Finish the call before opening the dialogue.',
    liveErrorUnconfigured: 'Voice calls are not configured on this server.',
    liveErrorMicDenied: 'Microphone access was refused. Allow it, then try again.',
    liveErrorMicUnsupported: 'This browser cannot capture a microphone.',
    liveErrorConnection: 'The call could not be connected.',
    liveErrorWorld: 'The world is no longer open.',
    liveErrorCharacter: 'This character has no nook to call from.',
    liveErrorRequest: 'The call request was rejected.',
    liveErrorVoice: 'This character has no usable voice.',
    liveErrorOffer: 'The audio offer was refused by the voice service.',
    liveErrorGeneric: 'The call failed.',
  },
  ja: {
    sceneChalk: 'シーン・チョーク',
    collapseScene: '導入をたたむ',
    expandScene: '導入を読む',
    world: 'ワールド',
    back: '前のシーンへ',
    writerPlaceholder: '作家に行動を伝える…',
    writerWriting: '作家が書いています…',
    ghostReused: 'この絵は既に持っていた',
    ghostFailed: '絵を描けなかった。',
    ghostUnreachable: '絵を表示できなかった。',
    sentToWriter: '作家に送りました',
    take: '手に取る',
    taken: '持ち物に加えました',
    backpack: '持ち物',
    characters: '登場人物',
    backpackHint: 'アイテムをカードや人物へドラッグ。キャンバスへ戻すこともできます。',
    backpackEmpty: '持ち物は空です。まずシーンの物を手に取ってください。',
    controls: 'ドラッグ：移動 · スクロール：拡大 · 扉：入る · Alt+← / Esc：戻る · 下の欄：行動',
    language: 'EN',
    mute: '音を消す',
    unmute: '音を出す',
    godHand: '神の手',
    worldFrozen: '世界停止中',
    pauseWorld: '世界の Agent を止める',
    thawWorld: '世界は停止中。クリックで再開',
    showControls: '操作方法を表示',
    hideControls: '操作方法を隠す',
    timestamp: '一日目 · 雨上がり 17:40',
    material: '素材',
    minimap: 'ミニマップ',

    nook: '小天地',
    nookBack: '小天地を出る',
    nookEmptyTitle: 'まだ何もない部屋',
    nookEmptyBody: '引っ越してきた跡だけが残っている。',
    nookEmptyPrompt: 'ここには、何があるべきだろう？',
    nookEmptyHint: '空欄のままなら、彼/彼女の来歴にふさわしいものが現れる。',
    nookInitSkip: 'スキップ',
    nookGenerating: '形になりつつある…',
    nookInitFailed: 'ここはまだ形にならなかった',
    nookError: '小天地を開けませんでした',
    nookRetry: '再試行',
    nookCoreStatus: 'ここに居る',

    liveCallStart: '声を出す',
    liveCallStop: '通話を切る',
    liveCallConnecting: '接続しています…',
    liveCallLive: '通話中',
    liveCallYou: 'あなた',
    liveCallThem: '相手の声',
    liveCallModalBlocked: '通話を終えてから会話を開いてください。',
    liveErrorUnconfigured: 'このサーバーでは音声通話が設定されていません。',
    liveErrorMicDenied: 'マイクの使用が拒否されました。許可してから再試行してください。',
    liveErrorMicUnsupported: 'このブラウザはマイクを取得できません。',
    liveErrorConnection: '通話に接続できませんでした。',
    liveErrorWorld: 'ワールドが開かれていません。',
    liveErrorCharacter: 'このキャラクターには通話できる小天地がありません。',
    liveErrorRequest: '通話の要求が拒否されました。',
    liveErrorVoice: 'このキャラクターには使える音色がありません。',
    liveErrorOffer: '音声のオファーが音声サービスに拒否されました。',
    liveErrorGeneric: '通話に失敗しました。',
  },
} as const;

export type UiCopy = (typeof UI_COPY)[Locale];
